### ISSUE TITLE
Define environment in deploy.rb

### ISSUE THREAD

**Issue by Dahie** [yeah/uberspacify#1]
Hey, first thanks for the awesome recipe!

Second, I want to deploy some rails apps, which don't need the test and the development environment that are setup in `mysql:setup_database_and_config`. Could you add a setting, to define an array of strings for the environments you want to setup.

I could imagine something along this lines:

`deploy.rb`

```
set :environments, %w(development production test)
```

`recipe.rb`

```
fetch(:environments).each do |env|
  […]
end
```

With fallback to the currently specified environments.

**Comment by yeah** [comment]
Since the number of databases is not limited on Uberspace or anything, I consider this a nice-to-have but it's not really needed. Feel free to re-open this, submit a pull request and I'll have a look.
