### ISSUE TITLE
Installation in a subdomain

### ISSUE THREAD

**Issue by simonszu** [yeah/uberspacify#5]
`# By default, your app will be available in the root of your Uberspace. If you
 # have your own domain set up, you can configure it here
 # set :domain, 'www.dummyapp.com'`

If i would want to install my rails app into a subdomain folder inside my wwwroot, how can i do this? Just set the domain for my subdomain, and the gem will automatically detect the right folder and installs the app inside it?

**Comment by yeah** [comment]
Yes. Just use `set :domain, 'mysubdomain.mydomain.com'`. This will create a folder and `.htaccess` in `/var/www/virtual/<username>/mysubdomain.mydomain.com` which is how Uberspace works with custom subdomains. You'd have to ask their team to activate the virtual host for your domain.
