### ISSUE TITLE
File-Uploads with (at least) Paperclip throw an Internal Server Error.

### ISSUE THREAD

**Issue by nocksock** [yeah/uberspacify#6]
When I try to upload a file to the server and process it using Paperclip I get an Internal Server Error. 

Content of the passenger-log:

```
2012/08/29 11:02:15 [crit] 20960#0: *77307 open() "/tmp/passenger-standalone.20728/client_body_temp/0000000047" failed (2: No such file or directory), client: 127.0.0.1, server: _, request: "POST /admin/big_slides/2 HTTP/1.1", host: "localhost:54369", referrer: "https://www.[…].de/admin/big_slides/2/edit"
2012/08/29 11:02:15 [crit] 20960#0: *77307 open() "/tmp/passenger-standalone.20728/client_body_temp/0000000048" failed (2: No such file or directory), client: 127.0.0.1, server: _, request: "POST /admin/big_slides/2 HTTP/1.1", host: "localhost:54369", referrer: "https://www.[…].de/admin/big_slides/2/edit"
```

I'll keep debugging. Probably some configuration-stuff.

**Comment by nocksock** [comment]
`ps fux` shows this nginx master process:

```
nginx: master process /home/bloomy/.passenger/standalone/3.0.15-x86_64-ruby1.9.3-linux-gcc4.1.2-1002/nginx-1.2.2/sbin/nginx -c /tmp/passenger-standalone.20728/config -p /tmp/passenger-standalone.20728/
```

But `/tmp/passenger-standalone.20728/` really does not exist. What's going on there?

**Comment by yeah** [comment]
Maybe you need to tell your Rails app specifically where you want your `tmp/` directory? Maybe Uberspace support can help you? If you figure it out, be sure to send me a pull request.

**Comment by yeah** [comment]
Leaving this open for you to close once you've fixed it :-)

**Comment by nocksock** [comment]
It turned out that somehow my tmp/ directory got deleted somehow. killing all processes and restarting fixed it.
